Models/WorkflowTemplate.cs
using System.ComponentModel.DataAnnotations;

namespace Systemize.Models
{
    public class WorkflowTemplate
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        public string? Description { get; set; }

        public List<Stage>? Stages { get; set; }






    }
}

Controllers/WorkflowTemplateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Systemize.Data;
using Systemize.Models;

namespace Systemize.Controllers
{
    public class WorkflowTemplateController : Controller
    {
        private readonly SystemizeContext _context;

        public WorkflowTemplateController(SystemizeContext context)
        {
            _context = context;
        }

        // GET: WorkflowTemplate
        public async Task<IActionResult> Index()
        {
            if (TempData["Message"] != null)
            {

                ViewBag.Message = TempData["Message"];

            }


            return View(await _context.WorkflowTemplate.Include(w => w.Stages).ToListAsync());
        }

        // GET: WorkflowTemplate/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workflowTemplate = await _context.WorkflowTemplate
                .Include(w => w.Stages)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workflowTemplate == null)
            {
                return NotFound();
            }

            return View(workflowTemplate);
        }

        // GET: WorkflowTemplate/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WorkflowTemplate/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] WorkflowTemplate workflowTemplate)
        {
            if (ModelState.IsValid)
            {

                _context.Add(workflowTemplate);
                _context.SaveChanges();
                var tmpID = workflowTemplate.Id;
                return RedirectToAction(nameof(StageAdd), new { id = tmpID });

                // return RedirectToAction(nameof(Index));
            }
            return View(workflowTemplate);
        }

        // GET: WorkflowTemplate/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workflowTemplate = await _context.WorkflowTemplate.FindAsync(id);
            if (workflowTemplate == null)
            {
                return NotFound();
            }
            return View(workflowTemplate);
        }

        // POST: WorkflowTemplate/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] WorkflowTemplate workflowTemplate)
        {
            if (id != workflowTemplate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workflowTemplate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkflowTemplateExists(workflowTemplate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(workflowTemplate);
        }

        // GET: WorkflowTemplate/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workflowTemplate = await _context.WorkflowTemplate
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workflowTemplate == null)
            {
                return NotFound();
            }

            return View(workflowTemplate);
        }

        // POST: WorkflowTemplate/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workflowTemplate = await _context.WorkflowTemplate
                .Include(w => w.Stages)

                .FirstOrDefaultAsync(m => m.Id == id);
            if (workflowTemplate != null)
            {


                _context.WorkflowTemplate.Remove(workflowTemplate);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        // GET: WorkflowTemplate/CreateWorkflowFromTemplate/5
        public async Task<IActionResult> CreateWorkflowFromTemplate(int? id)
        {
            var currentUser = getCurrentUser();


            if (id == null)
            {
                return NotFound();
            }

            var workflowTemplate = await _context.WorkflowTemplate
                .Include(w => w.Stages)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workflowTemplate == null)
            {
                return NotFound();
            }

            // Deep clone the workflowTemplate
            var newWorkflow = new Workflow
            {
                Name = workflowTemplate.Name + " - Copy",
                Description = workflowTemplate.Description,
                Stages = workflowTemplate.Stages?.Select(s => new Stage
                {
                    Name = s.Name,
                    Description = s.Description,
                    StageType = s.StageType,
                    Properties = s.Properties,
                    AssignedTo = s.AssignedTo,

                }).ToList()
            };

            newWorkflow.CreatedBy.Add(currentUser);
            newWorkflow.CreatedOn = DateTime.Now;
            newWorkflow.Status = "Draft";

            _context.Workflows.Add(newWorkflow);
            await _context.SaveChangesAsync();


            return RedirectToAction("Index", "Workflow");
            //return RedirectToAction(nameof(Details), new { id = newWorkflow.Id });
        }

        // GET: WorkflowTemplate/CreateWorkflowFromTemplate/5
        public async Task<IActionResult> CreateWorkflowFromTemplateAndStart(int? id)
        {
            var currentUser = getCurrentUser();


            if (id == null)
            {
                return NotFound();
            }

            var workflowTemplate = await _context.WorkflowTemplate
                .Include(w => w.Stages)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workflowTemplate == null)
            {
                return NotFound();
            }


            if (workflowTemplate.Stages.Count == 0)
            {
                TempData["Message"] = "Workflow has zero stages. Workflow must have one or more stages.";
                return RedirectToAction(nameof(Index));

            }


            // Deep clone the workflowTemplate
            var newWorkflow = new Workflow
            {
                Name = workflowTemplate.Name + "",
                Description = workflowTemplate.Description,
                Stages = workflowTemplate.Stages?.Select(s => new Stage
                {
                    Name = s.Name,
                    Description = s.Description,
                    StageType = s.StageType,
                    Properties = s.Properties,
                    AssignedTo = s.AssignedTo,
                }).ToList()
            };

            newWorkflow.CreatedBy.Add(currentUser);
            newWorkflow.CreatedOn = DateTime.Now;
            newWorkflow.Status = "Draft";

            _context.Workflows.Add(newWorkflow);
            await _context.SaveChangesAsync();

            var wid = newWorkflow.Id.ToString();
            //redirect to start workflow
            //Workflow / Action / [id] ? act = [action]
            return Redirect("/Workflow/Action/" + wid + "?act=Start");


        }





        // GET: WorkflowTemplate/Duplicate/5
        public async Task<IActionResult> Duplicate(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workflowTemplate = await _context.WorkflowTemplate
                .Include(w => w.Stages)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workflowTemplate == null)
            {
                return NotFound();
            }

            // Deep clone the workflowTemplate
            var newWorkflowTemplate = new WorkflowTemplate
            {
                Name = workflowTemplate.Name + " - Copy",
                Description = workflowTemplate.Description,
                Stages = workflowTemplate.Stages?.Select(s => new Stage
                {
                    Name = s.Name,
                    Description = s.Description,
                    StageType = s.StageType,
                    AssignedTo = s.AssignedTo,
                    Properties = s.Properties
                }).ToList()
            };

            _context.WorkflowTemplate.Add(newWorkflowTemplate);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = newWorkflowTemplate.Id });
        }




        // STAGE
        // GET: WorkflowTemplate/StageAdd/id
        [HttpGet]
        public IActionResult StageAdd(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                ViewData["WorkflowTemplateId"] = id;
            }


            if (TempData["Message"] != null)
            {

Views/WorkflowTemplate/Create.cshtml
@model Systemize.Models.WorkflowTemplate

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WorkflowTemplate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/WorkflowTemplate/Delete.cshtml
@model Systemize.Models.WorkflowTemplate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkflowTemplate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/WorkflowTemplate/Details.cshtml
@model Systemize.Models.WorkflowTemplate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>WorkflowTemplate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>





<div>
    <h4>Stages</h4>
    <div>
        <a asp-action="StageAdd" asp-route-id="@Model?.Id">Add a Stage</a> 

    </div>
    <hr />

    @if (Model.Stages != null)
    {

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => Model.Stages[0].Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => Model.Stages[0].Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => Model.Stages[0].StageType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => Model.Stages[0].StageStatus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => Model.Stages[0].AssignedTo)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model.Stages)
                {

                    <tr class="">
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StageType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StageStatus)
                        </td>
                        <td>
                            @if (item.AssignedTo != null)
                            {
                                @foreach (var assigned in item.AssignedTo)
                                {
                                    <span class="pr-3 "> @assigned </span>
                                   
                                }
                            }
                        </td>
            <td>
             
            </td>
        </tr>
                }
      
     </tbody>
</table>
       
    }
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/WorkflowTemplate/Edit.cshtml
@model Systemize.Models.WorkflowTemplate

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>WorkflowTemplate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <a asp-controller="WorkflowTemplate" asp-action="StageAdd" asp-route-id="@Model.Id"> Add another Stage</a>
            </div>
      


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/WorkflowTemplate/Index.cshtml
@model IEnumerable<Systemize.Models.WorkflowTemplate>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<div>
    <p style="display: inline-block; margin-right: 10px;">
        <a asp-action="Create">Create New</a>
    </p>
    <p style="display: inline-block;">
        <a asp-action="StageBuilder">Builder</a>
    </p>
</div>
<!-- response messages -->
@if (ViewData["Message"] != null && !String.IsNullOrEmpty(ViewData["Message"].ToString()))
{
    <div class="alert alert-success" role="alert">
        @ViewData["Message"].ToString()
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Duplicate" asp-route-id="@item.Id">Duplicate</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
                <td>
                    <a asp-action="CreateWorkflowFromTemplate" asp-route-id="@item.Id">Create Workflow From Template</a>
                </td>
                <td>

					
                        <a asp-action="CreateWorkflowFromTemplateAndStart" asp-route-id="@item.Id">Create Workflow From Template</a>
					
				
                   
                    
                </td>
        </tr>
}
    </tbody>
</table>

Views/WorkflowTemplate/StageAdd.cshtml
@model Systemize.Models.Stage

@{
    ViewData["Title"] = "Add a Stage";
}

<h1>Add a Stage</h1>

<h4>Stage</h4>
<hr />
<!-- response messages -->
@if (ViewData["Message"] != null && !String.IsNullOrEmpty(ViewData["Message"].ToString()))
{
    <div class="alert alert-success" role="alert">
        @ViewData["Message"].ToString()
    </div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="StageAdd">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StageType" class="control-label"></label>
                <input asp-for="StageType" class="form-control" />
                <span asp-validation-for="StageType" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="AssignedTo" class="control-label"></label>
                <input asp-for="AssignedTo" class="form-control" />
                <span asp-validation-for="AssignedTo" class="text-danger"></span>
            </div>
          
        
            <div class="form-group">
                <label asp-for="Properties" class="control-label"></label>
                <input asp-for="Properties" class="form-control" />
                <span asp-validation-for="Properties" class="text-danger"></span>
            </div>
       
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @{
        if (ViewData["WorkflowTemplateId"] != null)
		{
			var wfURL = "../Details/" + ViewData["WorkflowTemplateId"].ToString();
            <a href="@wfURL">Back</a>
		}
	
      
    }
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/WorkflowTemplate/StageBuilder.cshtml
@{
    ViewData["Title"] = "Add a Stage";
}


    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <style>
        .sortable, .draggable {
            min-height: 200px;
            padding: 10px;
            border: 1px solid #ccc;
            background-color: #f9f9f9;
        }
        .sortable {
            list-style-type: none;
        }
        .sortable li {
            margin: 5px;
            padding: 5px;
            border: 1px solid #ddd;
            background-color: #fff;
        }
    </style>


<h1>Stage Builder</h1>
<section> 
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h4>Current Stages</h4>
                <ul id="sortable" class="sortable">
                    <li class="ui-state-default">Stage 1</li>
                    <li class="ui-state-default">Stage 2</li>
                    <li class="ui-state-default">Stage 3</li>
                </ul>
            </div>
            <div class="col-md-6">
                <h4>Draggable Stages</h4>
                <ul id="draggable" class="sortable">
                    <li class="ui-widget-content">New Stage 1</li>
                    <li class="ui-widget-content">New Stage 2</li>
                    <li class="ui-widget-content">New Stage 3</li>
                </ul>
            </div>
        </div>
    </div>

    <script>
        $(function() {
            $("#sortable").sortable({
                placeholder: "ui-state-highlight"
            }).disableSelection();

            $(".ui-widget-content").draggable({
                connectToSortable: "#sortable",
                helper: "clone",
                revert: "invalid"
            });

            $("ul, div").disableSelection();
        });
    </script>
</section>




<div>
    <a asp-action="Index">Back to List</a>
</div>