Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Systemize.Data;
using Systemize.Models;
using Systemize.Models.ViewModel.Dashboard;


namespace Systemize.Controllers
{
    public class DashboardController : Controller
    {


        private readonly SystemizeContext _context;

        public DashboardController(SystemizeContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            string currentUser = getCurrentUser();

            DashboardEntire dashboardEntire = new DashboardEntire();

            //my assigned
            List<Workflow> myassigned = new List<Workflow>();

            // Fetch workflows assigned to the current user
            myassigned = await _context.Workflows
                .Where(w => w.AssignedTo.Contains(currentUser))
                .ToListAsync();

            dashboardEntire.myAssigned = myassigned;


            //my drafts
            List<Workflow> mydrafts = new List<Workflow>();

            // Fetch workflows assigned to the current user
            mydrafts = await _context.Workflows
                .Where(w => w.CreatedBy.Contains(currentUser) & w.Status == "Draft")
                .ToListAsync();

            dashboardEntire.myDrafts = mydrafts;



            //watchlist
            List<Workflow> mywatchlist = new List<Workflow>();
            var wf3 = await _context.Workflows.FirstOrDefaultAsync(m => m.Id == 1011);
            mywatchlist.Add(wf3);

            dashboardEntire.myWatchList = mywatchlist;

            return View(dashboardEntire);
        }

        public async Task<IActionResult> Metrics(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(s => s.Stages)
                .Include(h => h.History)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            MetricsEntire metricsEntire = new MetricsEntire();
            List<MetricsRow> metrics = new List<MetricsRow>();

            if (workflow.Stages != null && !workflow.Stages.IsNullOrEmpty())
            {
                foreach (var stage in workflow.Stages)
                {

                    var startHistory = workflow.History.FirstOrDefault(h => h.StageId == stage.Id && h.EventName == "Stage Started");
                    var finishHistory = workflow.History.FirstOrDefault(h => h.StageId == stage.Id && h.EventName == "Stage Completed");
                    int stageval = 0;
                    if (startHistory != null && finishHistory != null)
                    {
                        stageval = (int)(finishHistory.ExecutedAt - startHistory.ExecutedAt).TotalHours;
                    }

                    MetricsRow rw1 = new MetricsRow() { StageName = stage.Name, StageValue = stageval };
                    metrics.Add(rw1);
                }
            }

            metricsEntire.Rows = metrics;
            metricsEntire.workflowName = workflow.Name;

            return View(metricsEntire);
        }





        public async Task<IActionResult> TimeLine(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.History)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }


            return View(workflow);
        }



        private string getCurrentUser()
        {
            string email = "System";

            if (this.User != null)
            {
                if (this.User.Identity != null)
                {
                    if (this.User.Identity.IsAuthenticated)
                    {
                        email = this.User.Identity.Name;
                    }
                }
            }

            return email;
        }

    }
}

Controllers/WorkflowController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Systemize.Data;
using Systemize.Models;
using Systemize.Models.ViewModel.Workflow;
using Systemize.Services;


namespace Systemize.Controllers
{
    public class WorkflowController : Controller
    {
        private readonly SystemizeContext _context;

        public WorkflowController(SystemizeContext context)
        {
            _context = context;
        }




        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ChatSubmit(int id, [FromBody] string chat)
        {


            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.WorkflowForm)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            if (!System.String.IsNullOrEmpty(chat))
            {
                Console.Write(chat);
                if (workflow.WorkflowForm == null)
                {
                    workflow.WorkflowForm = new WorkflowForm();
                }

                //TODO process chat




            }


            return Ok("Data Received");
        }




        // GET: Workflow/FormBuilder/5
        [Authorize]
        public async Task<IActionResult> FormBuilder(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            //load workflow with eager loading
            var workflow = await _context.Workflows
                 .Include(w => w.WorkflowForm)
                 .FirstOrDefaultAsync(m => m.Id == id)
                 ;
            if (workflow == null)
            {
                return NotFound();
            }


            return View(workflow);
        }

        // GET: Workflow/FormRender/5
        [Authorize]
        public async Task<IActionResult> FormRender(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.WorkflowForm)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            if (workflow.WorkflowForm == null)
            {
                workflow.WorkflowForm = new WorkflowForm();
            }

            return View(workflow);
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> FormBuilderSubmit(int id, [FromBody] string data)
        {


            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.WorkflowForm)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            if (!System.String.IsNullOrEmpty(data))
            {
                Console.Write(data);
                if (workflow.WorkflowForm == null)
                {
                    workflow.WorkflowForm = new WorkflowForm();
                }


                workflow.FormData = data;
                _context.Workflows.Update(workflow);
                _context.SaveChanges();

            }


            return Ok("Data Received");
        }



        [HttpPost]
        [Authorize]
        public async Task<IActionResult> FormRenderSubmit(int id, [FromBody] string data)
        {

            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.WorkflowForm)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            if (!System.String.IsNullOrEmpty(data))
            {
                Console.Write(data);
                if (workflow.WorkflowForm == null)
                {
                    workflow.WorkflowForm = new WorkflowForm();
                }


                workflow.FormData = data;
                _context.Workflows.Update(workflow);
                _context.SaveChanges();

            }


            return Ok("Data Received");
        }



        // STAGE
        // GET: Workflow/StageAdd/id
        [HttpGet]
        [Authorize]
        public IActionResult StageAdd(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                ViewData["WorkflowId"] = id;
            }

            if (TempData["Message"] != null)
            {
                ViewData["Message"] = TempData["Message"].ToString();
            }


            return View();

        }


        // Replace the existing method with the following code
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> StageAdd(int? id, string? test)
        {
            var workflow = await _context.Workflows
                .Include(w => w.Stages)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workflow == null)
            {
                return NotFound();
            }

            var name = HttpContext.Request.Form["Name"];
            var description = HttpContext.Request.Form["Description"];
            var stagetype = HttpContext.Request.Form["StageType"];
            var assignedTo = HttpContext.Request.Form["AssignedTo"];

            if (assignedTo == "")
            {
                TempData["Message"] = "AssignedTo can't be empty";
                return RedirectToAction(nameof(StageAdd), new { id = id });
            }


            Stage stage = new Stage()
            {
                Name = name,
                Description = description,
                StageType = stagetype,
                AssignedTo = assignedTo.ToString().Split(';').ToList(),
                Properties = "{}",
                WorkflowId = workflow.Id
            };

            _context.Stages.Add(stage);
            await _context.SaveChangesAsync(); // This should now work with the correct using directive

            return RedirectToAction(nameof(Details), new { id = id });
        }



        // WORKFLOW


        // GET: Workflow
        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (TempData["Message"] != null)
            {

                ViewBag.Message = TempData["Message"];

            }


            return View(await _context.Workflows.ToListAsync());
        }

        // GET: Workflow/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {

            string currentUser = getCurrentUser();


            if (id == null)
            {
                return NotFound();
            }

            if (TempData["Action_Message"] != null)
            {
                ViewData["Action_Message"] = TempData["Action_Message"].ToString();
            }

            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.Stages)
                .Include(w => w.Documents)
                .Include(w => w.Tags)
                .Include(w => w.Links)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            Engine engine = new Engine(_context, workflow);
            WorkflowEntire workflowEntire = engine.AvailableActions(workflow, currentUser);


            workflowEntire.Workflow = workflow;
            return View(workflowEntire);

        }

        // GET: Workflow/Meta/5
        [Authorize]
        public async Task<IActionResult> Meta(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //load workflow with eager loading
            var workflow = await _context.Workflows
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            return View(workflow);
        }


        // GET: Workflow/stages/5
        [Authorize]
        public async Task<IActionResult> Stages(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.Stages)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            return View(workflow);
        }



        // GET: Workflow/History/5
        [Authorize]
        public async Task<IActionResult> History(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.History)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (workflow == null)
            {
                return NotFound();
            }

            return View(workflow);
        }

        // GET: Workflow/Notes/5
        [Authorize]
        public async Task<IActionResult> Notes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //load workflow with eager loading
            var workflow = await _context.Workflows
                .Include(w => w.Notes)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Systemize</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Systemize.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Systemize</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <!-- unauthenticated links
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        -->


                        <!-- unauthenticated links-->
                        @if (User.Identity.IsAuthenticated)
                        {

                            <!-- admin links-->
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AdminDashboard">Admin</a>
                                </li>
                            }
                            else
                            {


                                <!--
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UserDashboard">User</a>
                                </li>
                                -->
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="WorkflowTemplate" asp-action="Index">Template</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Workflow" asp-action="Index">Workflows</a>
                                </li>


                            }

                            <li class="nav-item ms-lg-auto d-flex align-items-center">
                                <form asp-controller="Account" asp-action="Logout" method="post" class="m-0 p-0">
                                    <button type="submit" class="btn btn-link nav-link text-dark p-0">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-lg-auto">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted" style="position:relative">
        <div class="container">
            &copy; 2025 - Systemize - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true" type="text/javascript"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js" type="text/javascript"></script>

 


  
  



  
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>